lots of tool simple configuration changes
M  .config/nvim/lua/plugins/lsp-zero.lua
M  .local/bin/anx
M  .local/bin/jkl
M  .local/bin/sendmail
M  .local/bin/start-tool
M  .local/share/backup.log
M  .newsboat/config

diff --git a/.local/bin/start-tool b/.local/bin/start-tool
--- a/.local/bin/start-tool
+++ b/.local/bin/start-tool
@@ -38,12 +38,26 @@ main() {
             if [ -x start ]; then
                 ./start
             else
-                . start
+                . start || nvim .
             fi
         else
-            start-tool "\$@"
+            out=\$(start-tool "\$@" 2>&1)
+            result=\$?
+
             if [ -x start ]; then
-                ./start "\$@"
+                out2=\$(./start "\$@" 2>&1)
+                result2=\$?
+
+                if [ \$result -eq 0 ]; then
+                    # echo "First succeeded..."
+                    echo "\$out" && [ \$result2 -eq 0 ] && echo "\$out2"
+                elif [ \$result2 -eq 0 ]; then
+                    # echo "Just Second succeeded..."
+                    echo "\$out2"
+                else
+                    # echo "Both failed..."
+                    echo "\$out" && echo "\$out2"
+                fi
             fi
         fi
     }
@@ -133,7 +147,7 @@ install() {
 
 # @cmd Extends your shell with special functions
 extend() {
-    depts=(tmux-send-cmd z send)
+    depts=(tmux-send-cmd z send gitv)
     regex=""
     for dept in "${depts[@]}"; do
         patterns="^$dept\(\)\s*\{([^{}]|\{[^{}]*\})*\}|^alias $dept"
